## Урок 7. Многомерный статистический анализ. Линейная регрессия

In [1]:
import pandas as pd
import numpy as np
from scipy import stats
import math

1. Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks): zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110], ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]. Используя математические операции, посчитать коэффициенты линейной регрессии, приняв за X заработную плату (то есть, zp - признак), а за y - значения скорингового балла (то есть, ks - целевая переменная). Произвести расчет как с использованием intercept, так и без.

In [2]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [3]:
X = zp.reshape((len(zp), 1))
X

array([[ 35],
       [ 45],
       [190],
       [200],
       [ 40],
       [ 70],
       [ 54],
       [150],
       [120],
       [110]])

In [4]:
Y = ks.reshape((len(ks), 1))
Y

array([[401],
       [574],
       [874],
       [919],
       [459],
       [739],
       [653],
       [902],
       [746],
       [832]])

#### C intercept

In [5]:
Xi = np.hstack([np.ones((len(zp), 1)), X])
Xi

array([[  1.,  35.],
       [  1.,  45.],
       [  1., 190.],
       [  1., 200.],
       [  1.,  40.],
       [  1.,  70.],
       [  1.,  54.],
       [  1., 150.],
       [  1., 120.],
       [  1., 110.]])

In [6]:
b = np.dot(np.linalg.inv(np.dot(Xi.T, Xi)), Xi.T @ Y)
print('intercept: {}, b: {}'.format(b[0][0], b[1][0]))

intercept: 444.17735732435943, b: 2.620538882402764


#### Без intercept

In [7]:
b = np.dot(np.linalg.inv(np.dot(X.T, X)), X.T @ Y)
print('b: {}'.format(b[0][0]))

b: 5.889820420132688


2. Посчитать коэффициент линейной регрессии при заработной плате (zp), используя градиентный спуск (без intercept).

In [8]:
def mse(B1, Y=Y, X=X, n=10):
    return np.sum((B1*X-Y)**2/n)

In [9]:
B1 = 0.1
alpha = 1e-7
n=10

In [10]:
for i in range(10000):
    B1 -=alpha*(2/n)*np.sum((B1*X-Y)*X)
    if i%500==0:
        print("Iteration{}, B1={}, mse={}".format(i, B1, mse(B1)))

Iteration0, B1=0.115952808, mse=515794.9112047831
Iteration500, B1=4.436601977832683, mse=85610.88627620286
Iteration1000, B1=5.524061455274668, mse=58359.886733764004
Iteration1500, B1=5.7977629451654105, mse=56633.60929660133
Iteration2000, B1=5.866650574656343, mse=56524.25426962639
Iteration2500, B1=5.883988826993857, mse=56517.326923148226
Iteration3000, B1=5.888352672815523, mse=56516.888094403395
Iteration3500, B1=5.88945100441116, mse=56516.860295784114
Iteration4000, B1=5.889727442292625, mse=56516.85853481644
Iteration4500, B1=5.889797018641524, mse=56516.85842326389
Iteration5000, B1=5.889814530236905, mse=56516.85841619733
Iteration5500, B1=5.889818937711242, mse=56516.85841574967
Iteration6000, B1=5.8898200470236475, mse=56516.858415721326
Iteration6500, B1=5.889820326225288, mse=56516.85841571954
Iteration7000, B1=5.889820396497239, mse=56516.85841571941
Iteration7500, B1=5.8898204141839114, mse=56516.85841571941
Iteration8000, B1=5.889820418635448, mse=56516.85841571941


3. В каких случаях для вычисления доверительных интервалов и проверки статистических гипотез используется таблица значений функции Лапласа, а в каких - таблица критических точек распределения Стьюдента?

В случаях, когда отсутствует информация о дисперсии, используется таблица значений функции Стьюдента, в остальных случаях - таблица значений функции Лапласа.

4. Произвести вычисления как в пункте 2, но с вычислением intercept. Учесть, что изменение коэффициентов должно производиться на каждом шаге одновременно (то есть изменение одного коэффициента не должно влиять на изменение другого во время одной итерации).

In [11]:
def mse_(B0, B1, Y=Y, X=X, n=10):
    return np.sum((B0+B1*X-Y)**2)/n

In [12]:
B1 = 0.1
B0 = 0.1
alpha = 1e-5
n=10

In [13]:
for i in range(2000000):
    B0 -=alpha*(2/n)*np.sum((B0+B1*X-Y))
    B1 -=alpha*(2/n)*np.sum((B0+B1*X-Y)*Xi)
    if i%100000==0:
        print("Iteration{}, B0={}, B1={}, mse={}".format(i, B0, B1, mse_(B0, B1)))

Iteration0, B0=0.1139932, B1=1.7090425419264001, mse=297194.39746170817
Iteration100000, B0=175.8269277563459, B1=4.600611240648842, mse=24737.65475870363
Iteration200000, B0=282.0002414920825, B1=3.817192171598172, mse=13142.283094678412
Iteration300000, B0=346.1658991649095, B1=3.3437342184614014, mse=8907.226394671019
Iteration400000, B0=384.9443028872792, B1=3.057600727148655, mse=7360.427743281287
Iteration500000, B0=408.3799637967812, B1=2.884676448850186, mse=6795.479919102792
Iteration600000, B0=422.5432647463698, B1=2.780169961728305, mse=6589.14017103219
Iteration700000, B0=431.1028310655597, B1=2.717011647823291, mse=6513.777297131714
Iteration800000, B0=436.2757900977293, B1=2.6788420305566913, mse=6486.252000548588
Iteration900000, B0=439.40205890046246, B1=2.6557742886838582, mse=6476.198748691538
Iteration1000000, B0=441.291414019284, B1=2.641833338964823, mse=6472.526930929462
Iteration1100000, B0=442.4332425024631, B1=2.6334081502254545, mse=6471.185847877958
Iteration